version: '2'
volumes:
    shared-data:
services:
  recorder:
    restart: always
    build: ./recorder
    privileged: true
    volumes:
      - 'shared-data:/data/sound_app'
  classifier:
    restart: always
    build: ./classifier
    privileged: true
    volumes:
      - 'shared-data:/data/sound_app'
  webserver:
    restart: always
    build: ./webserver
    volumes:
      - 'shared-data:/data/sound_app'
    ports:
      - 80:80
